apiVersion: v2
appVersion: 0.1.0
description: A Helm chart demonstrating the "sidecar" pattern
icon: https://logodownload.org/wp-content/uploads/2019/08/sumup-logo-5.png
name: sidecar
sources: [ "https://github.com/sumup/foo" ]
type: application
version: 0.3.0
